#!/usr/bin/env python3
'''Wrapper for evREwhere'''

import os
import sys

if sys.version_info[0] < 3:
    print('Python 3 is required for evREwhere to work')
    sys.exit(255)


if not os.environ.get('PYTHONDONTWRITEBYTECODE'):
    os.environ['PYTHONDONTWRITEBYTECODE'] = '1'
os.execvpe(sys.executable, [sys.executable, '-m', 'evrewhere.evrewhere'] + sys.argv[1:], os.environ)
