[tool.ruff]
src = ["evrewhere"]
line-length = 88
exclude = [".git"]
include = [
    "evre.py",
    "evrewhere/**/*.py",
    "examples/**/*.py",
    "**/pyproject.toml"
]
indent-width = 4

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = ["ANN002", "ANN003", "G004", "D107", "TRY400"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-line-length = 88

[tool.ruff.lint.pydocstyle]
convention = "google"
